### ISSUE TITLE
NatsError: Subject must be supplied

### ISSUE THREAD

**Issue by bahatron** [nats-io/stan.js#114]
I'm trying to write a listener worker, trying to connect as usual to the NATS server:

```ts
import $nats from "node-nats-streaming";
import { Message } from "node-nats-streaming";
import $logger from "../services/Logger";

const $stream = $nats.connect("test-cluster", "sync_repository_func");

$stream.subscribe("event").on("message", (msg: Message) => {
    const data = JSON.parse(<string>msg.getData());

    $logger.dump(data);
});

```

I get this error:

```
1|sync_repo  | NatsError: Subject must be supplied
1|sync_repo  |     at Client.publish (/app/node_modules/nats/lib/nats.js:1428:20)
1|sync_repo  |     at Client.request (/app/node_modules/nats/lib/nats.js:1654:10)
1|sync_repo  |     at Client.requestOne (/app/node_modules/nats/lib/nats.js:1732:17)
1|sync_repo  |     at Stan.subscribe (/app/node_modules/node-nats-streaming/lib/stan.js:677:13)
1|sync_repo  |     at Object.<anonymous> (/app/functions/sync_repository.ts:9:9)
1|sync_repo  |     at Module._compile (internal/modules/cjs/loader.js:774:30)
1|sync_repo  |     at Module.m._compile (/usr/local/lib/node_modules/pm2/node_modules/ts-node/src/index.ts:438:23)
1|sync_repo  |     at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
1|sync_repo  |     at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/pm2/node_modules/ts-node/src/index.ts:441:12)
```

Any ideas what's wrong?

I'm using:

dockerhub image `nats-streaming: latest`
library version: `0.2.2`

**Comment by aricart** [comment]
@bahatron you are trying to subscribe before the client connected.

You should set up your subscription after you get a 'connect' event. [See basic usage here](https://github.com/nats-io/stan.js#basic-usage).
