### ISSUE TITLE
Can not connect to NATS using code from Basic Usage example

### ISSUE THREAD

**Issue by vasergen** [nats-io/stan.js#150]
Got this error during trying to connect to NATS using `Basic Usage` example

```
events.js:174
      throw er; // Unhandled 'error' event
      ^
NatsError: stan: connect request timeout
    at Object.nc.requestOne [as callback] (/home/vlgk/github/hotwohnung/worker/node_modules/node-nats-streaming/lib/stan.js:323:27)
    at Timeout.conf.timeout.setTimeout (/home/vlgk/github/hotwohnung/worker/node_modules/nats/lib/nats.js:1843:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
Emitted 'error' event at:
    at Stan.closeWithError (/home/vlgk/github/hotwohnung/worker/node_modules/node-nats-streaming/lib/stan.js:414:10)
    at Object.nc.requestOne [as callback] (/home/vlgk/github/hotwohnung/worker/node_modules/node-nats-streaming/lib/stan.js:325:22)
    at Timeout.conf.timeout.setTimeout (/home/vlgk/github/hotwohnung/worker/node_modules/nats/lib/nats.js:1843:14)
    [... lines matching original stack trace ...]
    at Timer.processTimers (timers.js:223:10)
```

**Comment by vasergen** [comment]
figured it out that `nats` has different docker image for streaming, so close it

**Comment by mirajehossain** [comment]
> figured it out that `nats` has different docker image for streaming, so close it

I'm using `https://hub.docker.com/_/nats-streaming` this docker image but still got the same error.

**Comment by aricart** [comment]
@mirajehossain you should be looking at JetStream if you instead of nats-streaming....

**Comment by rabeeshcharles** [comment]
It looks JetStream supports only with typescript and not javascript..

I just go through this link - https://github.com/nats-io/nats.deno

**Comment by aricart** [comment]
Typescript compiles into JS, this helps us. However you can just consume from JavaScript.
