### ISSUE TITLE
Incompatible with Jest 26

### ISSUE THREAD

**Issue by lw-mgr** [nats-io/stan.js#177]
With Jest v25 my test suite runs fine, but with jest 26 im getting an error which points to an error in the nats package:

```
      Failure: Cannot coerce to Uint8Array: object
        at new goog.asserts.

      at Object.goog.asserts.fail (../../node_modules/google-protobuf/google-protobuf.js:84:89)
      at Function.jspb.Message.bytesAsU8 (../../node_modules/google-protobuf/google-protobuf.js:423:432)
      at proto.pb.ConnectRequest.getConnId_asU8 (../../node_modules/node-nats-streaming/lib/pb/protocol_pb.js:1622:51)
      at Function.proto.pb.ConnectRequest.serializeBinaryToWriter (../../node_modules/node-nats-streaming/lib/pb/protocol_pb.js:1516:15)
      at proto.pb.ConnectRequest.serializeBinary (../../node_modules/node-nats-streaming/lib/pb/protocol_pb.js:1481:27)
      at Stan.initConnection (../../node_modules/node-nats-streaming/lib/stan.js:308:55)
      at Client.<anonymous> (../../node_modules/node-nats-streaming/lib/stan.js:371:10)
      at Client.connectCB (../../node_modules/nats/lib/nats.js:658:8)
      at ../../node_modules/nats/lib/nats.js:1250:20
      at Client.processInbound (../../node_modules/nats/lib/nats.js:1184:13)
      at Socket.<anonymous> (../../node_modules/nats/lib/nats.js:820:10)
```

**Comment by aricart** [comment]
@lw-mgr  - looks like this is a recurring issue with Jest. This issue seems to point to a work-around: https://github.com/facebook/jest/issues/7780
